#!/bin/bash
nix-shell --command "cd manager ; cargo fmt --check"
nix-shell --command "cd kcf/tools/task-manager/ ; black --check kcf_tasks"
nix-shell --command "cd kcf/tools/screencasts/ ; cargo fmt --check"
