baseURL = "https://gradesta.com/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "gradesta - audio native computing"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Features"
url = "#service"
weight = 3
[[menu.main]]
name = "Devlog"
url = "/blog"
weight = 4

# Sitemap Menu
[[menu.sitemap]]
name = "Open source project"
url = "https://gradesta.org"
weight = 1
[[menu.sitemap]]
name = "Github"
url = "https://github.com/gradesta/gradesta"
weight = 2
[[menu.sitemap]]
name = "Ethical codex"
url = "https://github.com/gradesta/gradesta/blob/default/gradesta-s.r.o.-commercial-stuff/ethical_codex.md"
weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All rights reserved copyright © gradesta s.r.o. 2022"
footerLogo = "https://assets.gradesta.com/long-path-light-t.png"
logo = "https://assets.gradesta.com/long-logo-t.png"

[params.address]
address = "Benešovská 33/1858, Praha 10, 101 00, Czech Republic"
ico = "14207486"
email = "goodnight@gradesta.com"
openingHours = "10:00-22:00 CET"
phone = "+(420) 910 121 354"


[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/company/gradesta-s-r-o"
weight = 2
