//! Local services discovery from gradesta-service-manager
//!
//! This module loads the browser-services.json file generated by
//! gradesta-service-manager to discover locally running services.

use serde::Deserialize;
use std::path::PathBuf;

/// A local service entry
#[derive(Debug, Clone, Deserialize)]
pub struct LocalService {
    pub name: String,
    pub url: String,
}

/// Local services configuration loaded from browser-services.json
#[derive(Debug, Clone, Deserialize)]
pub struct LocalServices {
    pub servers: Vec<LocalService>,
    pub elves: Vec<LocalService>,
}

impl LocalServices {
    /// Load local services from the standard config location
    pub fn load() -> Option<Self> {
        let config_dir = dirs::config_dir()?;
        let browser_services_path = config_dir
            .join("gradesta")
            .join("services")
            .join("browser-services.json");

        Self::load_from_path(&browser_services_path)
    }

    /// Load local services from a specific path
    pub fn load_from_path(path: &PathBuf) -> Option<Self> {
        if !path.exists() {
            return None;
        }

        let content = std::fs::read_to_string(path).ok()?;
        serde_json::from_str(&content).ok()
    }
}
