name: Publish website

on: [push]

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest
    environment: "FTP deploy"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true
          
          
      - name: Build
        working-directory: gradesta-s.r.o.-commercial-stuff/web
        run: hugo
          
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: "${{ secrets.FTP_SERVER }}"
          username: "${{ secrets.FTP_USERNAME }}"
          password: "${{ secrets.FTP_PASSWORD }}"
          protocol: ftps
          local-dir: gradesta-s.r.o.-commercial-stuff/web/public/
          server-dir: www/domains/gradesta.com/
          state-name: ../.ftp-deploy-sync-state.json
