name: Test manager

on:
  push:
    paths:
      - manager/**
      - .github/workflows/test-manager.yml
  workflow_dispatch: {}

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v17
        with:
           nix_path: nixpkgs=channel:nixos-22.05

      - name: Check cargo-fmt on manager
        run: nix-shell --command "cd manager ; cargo fmt --check"
      - name: Test manager
        run: nix-shell --command "cd manager ; LANG=en cargo tarpaulin --implicit-test-threads --fail-under 64"
      - name: Test that one flaky test that fails if other threads are working with disk
        run: nix-shell --command "cd manager ; LANG=en cargo test -- --ignored"
