name: Test manager

on:
  push:
    paths:
      - manager/**
      - .github/workflows/test-manager.yml
  workflow_dispatch: {}

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v17
        with:
           nix_path: nixpkgs=channel:nixos-22.05

      - name: Test manager
        run: nix-shell --command "cd manager ; cargo test"
