name: Test manager

on:
  push:
    paths:
      - manager/**
      - .github/workflows/test-manager.yml
  workflow_dispatch: {}
  
  run-ci-tests:
    runs-on: ubuntu-latest
    needs: build-ci-docker-image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v17
        with:
           nix_path: nixpkgs=channel:nixos-unstabl

      - name: Test manager
        run: nix-shell --command "cd manager ; cargo test"
