name: Test manager

on:
  push:
    paths:
      - manager/**
      - .github/test-manager.yml
  workflow_dispatch: {}
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test
        uses: docker://nixos/nix
        with:
          args: nix-shell --command "cargo test"
