name: Test manager

on:
  push:
    paths:
      - manager/**
      - .github/test-manager.yml
  workflow_dispatch: {}
  
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix
      options: --user root # https://stackoverflow.com/questions/68578638/how-to-checkout-repo-inside-the-docker-in-github-action

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: nix-shell
      - run: cd manager ; cargo test
