name: Test manager

on:
  push:
    paths:
      - manager/**

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: nix-shell
      - run: cd manager ; cargo test

        
