name: Test kcf-tasks

on:
  push:
    paths:
      - kcf/tools/kcf_tasks/**
      - .github/workflows/test-kcf-tasks.yml
  workflow_dispatch: {}

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kcf/tools/kcf_tasks/
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8
      - name: Setup virtualenv
        run: python -m venv venv
      - name: install dependencies
        run: ./venv/bin/pip install -r requirements-dev.txt -r requirements.txt
      - name: Check black on kcf_tasks
        run: ./venv/bin/black --check kcf_tasks
      - name: Test kcf_tasks
        run: ./venv/bin/pytest kcf_tasks --cov --cov-fail-under=17
