name: Test manager

on:
  push:
    paths:
      - docker/ci-tests/**
      - manager/**
      - .github/workflows/test-manager.yml
  workflow_dispatch: {}
  
jobs:
  ci-docker-image:
    runs-on: ubuntu-latest
    environment: "Gradesta CI docker hub"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/ci-tests/.
          push: true
          tags: timthelion/gradesta-ci-test:latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test
        uses: docker://timthelion/gradesta-ci-test
        with:
          args: nix-shell --command "cd manager ; cargo test"
