name: Test kcf screencasts tool

on:
  push:
    paths:
      - kcf/tools/screencasts/**
      - .github/workflows/test-kcf-screencasts.yml
  workflow_dispatch: {}

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v17
        with:
           nix_path: nixpkgs=channel:nixos-22.05

      - name: Check cargo-fmt
        run: nix-shell --command "cd kcf/tools/screencasts ; cargo fmt --check"

      - name: Run tests
        run: nix-shell --command "cd kcf/tools/screencasts ; cargo tarpaulin --implicit-test-threads --fail-under 64"
      - name: Run tests that aren't tarpaulin compatible
        run: nix-shell --command "cd manager ; cargo test -- --ignored"
